services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: unitask
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      REDIS_HOST: redis 
    volumes:
      - ./:/var/www
    networks:
      - laravel
    ports:
      - "9000:9000"

  redis:
    image: redis:alpine
    container_name: laravel_redis
    networks:
      - laravel

  reverb:
    build: .
    container_name: reverb
    command: php artisan reverb:start --host=0.0.0.0 --port=8080
    ports:
      - "8080:8080"
    depends_on:
      - app
      - redis
    networks:
      - laravel

  queue-worker:
    build: .
    container_name: laravel_worker
    restart: unless-stopped
    command: php artisan queue:work
    depends_on:
      - app
      - redis
    networks:
      - laravel

  db:
    image: postgres:16-alpine
    container_name: laravel_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: unitask
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata: